### ISSUE TITLE
Console or WinForms based OAuth2 example.

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#10]
Question

I just don't see how from a forms based application you could use the OAuth2 as it requires a redirect URL.  This is easy within a webApp.

Any ideas how you would handle authorisation from a Console or WinForms based app?

Maybe a sample snippet would be good.

**Comment by jhoerr** [comment]
My understanding is that the only way to authenticate with Box is through their website.  The redirect URL can have a custom scheme (e.g. myscheme://foo) which can be hooked by the client application.  I haven't messed around with this, but Box provides [some direction](http://developers.box.com/authentication-in-your-ios-app/).  That example is iOS-specific, but I think the idea is generally applicable.

**Comment by mascon** [comment]
OK I read it and I that is very iOS I can not find anything like that in .NET.  Any ideas how to capture the redirect information would be a great help.

**Comment by jhoerr** [comment]
This [StackOverflow question](http://stackoverflow.com/questions/80650/how-do-i-register-a-custom-url-protocol-in-windows) might get you pointed in the right direction.

**Comment by mascon** [comment]
Yep I looked at that one, but this just invokes an external application and not a hook into your running app.

**Comment by jhoerr** [comment]
Hrm.. I'm not altogether sure, then.  Maybe the Box platform folks would have some advice?
