### ISSUE TITLE
Missing Feature from Enterprise User Update

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#12]
There is a special feature for enterprise users.

To roll a user out of the enterprise (and convert them to a standalone free user), to activate this you should update the special enterprise attribute to be null and a notify URL parameter is also available to suppress update.

I think this would be best created as a new event.

BoxClient.RollOutUser(Userid)

I would suggest this is not added to the standard update 

BoxClient.UpdateUser(ManagedUser)

**Comment by jhoerr** [comment]
Is this up on the API documentation?  I'm not seeing it.

On Mon, Jan 7, 2013 at 10:28 AM, mascon notifications@github.com wrote:

> There is a special feature for enterprise users.
> 
> To roll a user out of the enterprise (and convert them to a standalone
> free user), to activate this you should update the special enterprise
> attribute to be null
> 
> I think this would be best created as a new event.
> 
> BoxClient.RollOutUser(Userid)
> 
> I would suggest this is not added to the standard update
> 
> BoxClient.UpdateUser(ManagedUser)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/12.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by mascon** [comment]
First paragraph tells about this feature and the attribute is the first on the list.

http://developers.box.com/docs/#users-update-a-users-information

**Comment by jhoerr** [comment]
Ah, ok -- that's a new field too.  Thanks for letting me know!

On Mon, Jan 7, 2013 at 11:44 AM, mascon notifications@github.com wrote:

> First paragraph tells about this feature and the attribute is the first on
> the list.
> 
> http://developers.box.com/docs/#users-update-a-users-information
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/12#issuecomment-11959154.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by mascon** [comment]
Yes but I would not expose if as a field.  You only get need it for this one feature so I would as I suggest create a function that sets this attribute only to rollout the user.

**Comment by jhoerr** [comment]
Added Client.ConvertToStandaloneUser() in 6ea57d322953f50f3fd44661245ba503048de25c
