### ISSUE TITLE
Getting to the status codes

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#14]
Can you provide a code snippet showing how to get to the error results of the BOX update

Like the 200, 300. 400. 500 events

I did not find one in your tests and samples

**Comment by jhoerr** [comment]
Try this:

``` csharp
try
{
    // Try to fetch one of my folders...
    Client.GetFolder("482710136");
}
catch (BoxException e)
{
    // Should be a 403: Forbidden
    Console.Out.WriteLine(e.HttpStatusCode);
}
```

**Comment by mascon** [comment]
That works fine.  Should I just except that if I do not get an exception the call received a 2XX response?

The reason I ask is I am making update calls that are not updating the users.  However no exception is thrown

**Comment by jhoerr** [comment]
Yep -- BoxExceptions are only thrown when the client determines that
something bad has happened.

On Mon, Jan 7, 2013 at 3:09 PM, mascon notifications@github.com wrote:

> That works fine. Should I just except that if I do not get an exception
> the call received a 2XX response?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/14#issuecomment-11969048.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581
