### ISSUE TITLE
ChangePrimaryLogin Throws Bad Request Exception Information not available

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#15]
When using this code The user does not get updated and the ex.Message throws an exception.

```
                    Try

                        ManagedUser = BoxClient.ChangePrimaryLogin(ManagedUser.Id, "newemail@domain.com")

                    Catch ex As BoxException

                        Debug.WriteLine("Update results:" & ex.HttpStatusCode)
                        Debug.WriteLine("Update results:" & ex.Message)

                    End Try
```

This appears to be the only way to change a users e-mail address in API V2. 

POSTMan also returns a 400 error but I should be able to get to the message without it causing an exception I believe?

**Comment by jhoerr** [comment]
BoxException should now properly provide Message and Code information as of 4ce1c9c37b92db86ba5e8cb5209fef000a10e69a.

**Comment by jhoerr** [comment]
Debugging ideas, off the top of my head:  
- Is 'newemail@domain.com' an existing email alas for the user?
- Has that alias been confirmed?
- Is the domain non-public and associated with your enterprise?

As I read the documentation all of those must be true in order for that request to work.

**Comment by mascon** [comment]
Yep works far better now thanks. 

Sent from my BlackBerry® wireless device

-----Original Message-----
