### ISSUE TITLE
Question and Potential Issue with CreateFolder

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#18]
When I call the following SDK item

BoxClient.CreateFolder(BoxFolder.Id, DepartmentalInfo.DirectoryName)

Nothing is always returned in the Path and PathID

Is this correct?

**Comment by jhoerr** [comment]
Yes, that's expected.  See also [this question](http://stackoverflow.com/questions/12588488/include-path-path-id-with-folder-object) on StackOverflow.

**Comment by mascon** [comment]
That is a pain then :-(  did you get any feedback from box on your request.

**Comment by jhoerr** [comment]
No, I didn't.  :\

On Fri, Jan 25, 2013 at 11:33 AM, mascon notifications@github.com wrote:

> That is a pain then :-( did you get any feedback from box on your request.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/18#issuecomment-12708512.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by mascon** [comment]
What is the path_collection that is part of the folder object?

I do not think that the SDK handles that yet either?

Can you look into it and see if this is already supported.

**Comment by jhoerr** [comment]
I think path_collection is a new-to-me feature.  I expect that it took the
place of path and path_ids for both files and folders.  I'll get that
implemented asap.

On Fri, Jan 25, 2013 at 2:17 PM, mascon notifications@github.com wrote:

> What is the path_collection that is part of the folder object?
> 
> I do not think that the SDK handles that yet either?
> 
> Can you look into it and see if this is already supported.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/18#issuecomment-12716188.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by jhoerr** [comment]
support for path_collection implemented in 7d19781a9b318362f45eda365d145c4e6ab4fdcf

**Comment by mascon** [comment]
Thanks and already using the new path collections object :-)
