### ISSUE TITLE
Unable to add multi line descriptions.

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#19]
When adding descriptions to folders I can not add multi line descriptions.

Calling the following boxClient.UpdateFolderDescription(folder.ID, "This is my description%0AThis is my secondline")

In API V1 I was able to pass the following on the URL

description=This is line one%0AThis is line two%0AThis is line three.

Now if I pass the %0A it just gets added into the description when using the SDK

How should I now add multi-line descriptions?

**Comment by jhoerr** [comment]
I don't know -- I've never tried.  Perhaps you can create a multi-line
description at Box's site, fetch it via the SDK, and see how it's encoded
in JSON?

On Fri, Jan 25, 2013 at 10:42 AM, mascon notifications@github.com wrote:

> When adding descriptions to folders I can not add multi line descriptions.
> 
> Calling the following boxClient.UpdateFolderDescription(folder.ID, "This
> is my description%0AThis is my secondline")
> 
> In API V1 I was able to pass the following on the URL
> 
> description=This is line one%0AThis is line two%0AThis is line three.
> 
> Now if I pass the %0A it just gets added into the description when using
> the SDK
> 
> How should I now add multi-line descriptions?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/19.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by mascon** [comment]
Well the result is a \n

however adding that in the string when using the SDK just puts it in the single line again?

Trying with POSTMAN directly returns the correct results.

Any chance you can look at this to see if it is a quick fix?

**Comment by jhoerr** [comment]
When I set the description to "new\ndescription" it appears to work as expected.  I verified that it creates a multi-line description at Box's site.
