### ISSUE TITLE
Small Change in the User Object

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#20]
There is a new collection in the user object.

EXAMPLE USER
{
    "type": "user",
    "id": "181216415",
    "name": "sean rose",
    "login": "sean+awesome@box.com",
    "created_at": "2012-05-03T21:39:11-07:00",
    "modified_at": "2012-11-14T11:21:32-08:00",
    "role": "admin",
    "language": "en",
    "space_amount": 11345156112,
    "space_used": 1237009912,
    "max_upload_size": 2147483648,
    "tracking_codes": [],
    "can_see_managed_users": true,
    "is_sync_enabled": true,
    "status": "active",
    "job_title": "",
    "phone": "6509241374",
    "address": "",
    "avatar_url": "https://www.box.com/api/avatar/large/181216415",
    "is_exempt_from_device_limits": false,
    "is_exempt_from_login_verification": false,
    "enterprise": {
        "type": "enterprise",
        "id": "17077211",
        "name": "seanrose enterprise"
    }
}

Could this be added to the SDK user object along with the other missing update elements

**Comment by jhoerr** [comment]
Can do -- thanks for the heads up.

On Thu, Jan 31, 2013 at 10:56 AM, mascon notifications@github.com wrote:

> There is a new collection in the user object.
> 
> EXAMPLE USER
> {
> "type": "user",
> "id": "181216415",
> "name": "sean rose",
> "login": "sean+awesome@box.com",
> "created_at": "2012-05-03T21:39:11-07:00",
> "modified_at": "2012-11-14T11:21:32-08:00",
> "role": "admin",
> "language": "en",
> "space_amount": 11345156112,
> "space_used": 1237009912,
> "max_upload_size": 2147483648,
> "tracking_codes": [],
> "can_see_managed_users": true,
> "is_sync_enabled": true,
> "status": "active",
> "job_title": "",
> "phone": "6509241374",
> "address": "",
> "avatar_url": "https://www.box.com/api/avatar/large/181216415",
> "is_exempt_from_device_limits": false,
> "is_exempt_from_login_verification": false,
> "enterprise": {
> "type": "enterprise",
> "id": "17077211",
> "name": "seanrose enterprise"
> }
> }
> 
> Could this be added to the SDK user object along with the other missing
> update elements
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhoerr/box-csharp-sdk-v2/issues/20.

## 

John Hoerr
jhoerr@gmail.com
503.360.6581

**Comment by jhoerr** [comment]
I added support for the new Enterprise field in 6ea57d322953f50f3fd44661245ba503048de25c.  Also added a method, Client.ConvertToStandaloneUser(), that will roll the user out of the enterprise.  I haven't been able to verify that this works -- I get a 403 response and a note saying that I don't have high enough privileges to roll a user out of an enterprise.  But that suggests to me that the request is properly formed.
