### ISSUE TITLE
GetFolders appears to be missing this element

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#21]
When I get a list of folders I do not see in the returned values this element

sync_state 

It is listed as an element in the box documentation for folders. 

OK here is the call needed.

https://api.box.com/2.0/folders/0/items?fields=sync_state

This would be really helpful... god I wish I was a C# programmer

**Comment by jhoerr** [comment]
That's a new field.  I'll get it added.

**Comment by mascon** [comment]
Thanks. We have been needing this for ages. Is it a big change or one I can expect in your normal 1-2 hour scheduling :-)

Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by jhoerr** [comment]
Folder.SyncState is now available as a string in cfc3138862171a066d641e3a216cd3372fdec96a.  I will change this to an enum when I can figure out all of the possible values.

**Comment by jhoerr** [comment]
Oh and I should mention that Box does not appear to return sync_state unless it's explicitly requested.

**Comment by prexer** [comment]
That's correct.   We generally didn't think most clients would care about the sync_state, and didn't want to clutter up the responses.   Possible values:  not_synced, partially_synced, and synced

**Comment by jhoerr** [comment]
Thanks Peter!

**Comment by mascon** [comment]
Can these an object like the status Active and inactive ?  This would be nice for all predefined return types.

**Comment by jhoerr** [comment]
Yep.  Thanks to Peter's comment I can now enumerate the range of possible values.  Look for this today.

**Comment by jhoerr** [comment]
Enumerated values in 13975648a23dfb13864530a016b0394a834c1b77.  If the sync_state is not requested, the value of Folder.SyncState will be 'SyncState.Unknown'.
