### ISSUE TITLE
Fields - Design question

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#22]
Would it be possible to define the fields into categories.

Of course Box Ignores if we send rubbish fields but the SDK is a interface to the API.

Let me give an example  we have fields a number of unique field types that are really specific for only a folder for example

sync_state

which could be confused with the user field

Is_Sync_Enabled  

It would be better if sending to a folder we only can choose folder fields.  If addressing a file then only file fields and of course this goes for each type.

Of course i flip backwards and forwards to the box documentation to see what fields are required per object type but this might be better if the SDK guided me to the correct ones so I cannot make mistakes.

Just a thought as I selected the wrong one in testing last night.

**Comment by jhoerr** [comment]
I've been thinking about this.  The Fields enum used to be much less crowded and applied only to Files and Folders (where there was ~90% overlap.)  When Users were added, the number of fields doubled and just continues to grow.  So the situation now does indeed feel rather unwieldy.  

I'll break out FileFields, FolderFields, etc.  It'll be a breaking change but it's for the best in the long-term.

**Comment by mascon** [comment]
Agreed

**Comment by mascon** [comment]
Implemented as as far as I can see working well now.  Thanks
