### ISSUE TITLE
Missing ability to remove shared link

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#28]
I can find the solution to create a shared link but not remove one.  Can this be added?

From the Box Pages

http://developers.box.com/docs/#folders-create-a-shared-link-for-a-folder

In order to disable a shared link, send this same type of PUT request with the value of shared_link set to null, i.e. {"shared_link": null}

**Comment by jhoerr** [comment]
Added in b47866b67b8349e232a11d9b740d9c4533926076.  Use Client.DisableSharedLink().
