### ISSUE TITLE
New feature for inclusion GZIP

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#30]
Box API can now send responses compressed for faster load times.

Here is the text from the developer pages.  The info is found in the general area near the CORS info.

gzip
If you would like responses from Box to be compressed for faster response times, simply include an Accept-Encoding header with a value of gzip, deflate, and responses will be gzipped.

**Comment by jhoerr** [comment]
Fortunately for us RestSharp already includes this header by default. :)

**Comment by mascon** [comment]
Perfect.  I thought it was new as I did not notice it on the Box site before.  Silly me :-)

**Comment by jhoerr** [comment]
It could be new -- I don't know that I've seen it before either.  The RestSharp library that handles the HTTP side of things always has this enabled, so we just got lucky on this one!
