### ISSUE TITLE
Request for new extention

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#31]
As part of the admin interface for users you see the following interesting information.

![Box request](https://f.cloud.github.com/assets/3042313/208783/0304d428-824a-11e2-9f27-3e890a61700a.jpg)

This can be found by trawling through the events API for the user.  However that seems a labour intensive task.  

Any idea how we might be able to make this into an extension and find a way to return it even if it takes time.

I have asked for this to be added to the API "user" objects via Box account management but that might take some time.

**Comment by jhoerr** [comment]
Was this supported in the V1 API?

**Comment by jhoerr** [comment]
I think you had a good insight about writing a wrapper-based extension and I'm wondering if we can do the same here.

**Comment by mascon** [comment]
I wish it was or I would have been heading there for it :-)  

What this is represents the last action taken by the user in their events stream.  Now what we really need is to be able to reverse the lookup of events starting with the last one.

Of course this does not exist and we also can not filter events which would also be a nice feature of the events endpoint.

**Comment by jhoerr** [comment]
There currently isn't a way to filter enterprise events by the user that generated them.  Let's revisit this if/when that level of filtering is supported.
