### ISSUE TITLE
Change in Supported Filenames

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#34]
Filenames with characters \ / ” : < > | \* ? and filenames with leading or trailing whitespace or periods are not allowed.

Not sure is this is checked in the SDK but it appears that periods are now NOT allowed.

**Comment by jhoerr** [comment]
> it appears that periods are now NOT allowed.

Erm, this would be very very bad.  But the docs I see only suggest that colons aren't allowed.  Are you unable to create files with periods in them?

**Comment by mascon** [comment]
Well it appears to have been changed on the site now :-).  Test above was a direct copy and paste action.
