### ISSUE TITLE
Creating a shared link

### ISSUE THREAD

**Issue by everettevola** [jhoerr/box-csharp-sdk-v2#35]
I am having trouble creating a shared link on a file.  From what I can tell on the box developer documentation, only the "Access" property must be set on the SharedLink object prior applying it to a file.  The following code is failing with a BoxException.

SharedLink sharedLink = new SharedLink() 
{ 
    Access = BoxApi.V2.Model.Enum.Access.Collaborators
};
file = _manager.ShareFileLink(file, sharedLink);

Can you point me in the right direction?

**Comment by everettevola** [comment]
I have been looking through your source code and something struck me as odd.  In Permissions.cs, BoxApi.V2.Model, the CanDownload property has JsonProperty attribution for "item_collection".  Shouldn't this attribution point to "can_download"?

I am not sure if this is related to the issue I am having in my initial comment above, but it does look suspicious.

**Comment by jhoerr** [comment]
Both things are bugs.  I've added tests and fixed the issues.  Will commit them shortly!

**Comment by jhoerr** [comment]
Fixed in 35d85fefc2dcd5ac905b74d5fc739075f9bb1e39.  Let me know if you still have any problems.

**Comment by ibelong2sathish** [comment]
There is an issue with shareLink, it is throwing the error as "Bad Request".

The code that I had used to generate the shared link as follows:

Dim expectedLink As SharedLink = New SharedLink(BoxApi.V2.Model.Enum.Access.Open, Permissions:=New Permissions() With {.CanDownload = True, .CanPreview = True})
Dim linkedFile As File = objBox.ShareLink(objFile, expectedLink)

Kindly point me with the right direction..

**Comment by elattoo** [comment]
Hello. I'm having the "Bad Request" issue as well. Anybody still monitoring this? I'm using v2 c# api. 

```
BoxFile file = boxManager.CreateFile(folder, fileName, fileStream);
file.Description = descriptiveTags;
boxManager.Update(file);
SharedLink sharedLink = new SharedLink(BoxApi.V2.Model.Enum.Access.Open);
BoxFile linkedFile = boxManager.ShareLink(file, sharedLink);
boxManager.Delete(linkedFile);
```

It barfs on the "ShareLink" attempt. Everything prior is working fine. BoxFile is an alias for BoxApi.V2.Model.File, and BoxFolder = BoxApi.V2.Model.Folder.

Thanks!
Kevin
