### ISSUE TITLE
Extension of the SDK to update user.

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#4]
Dear Reader

The API V2 is now officially released as GA of today (14/12/2012).  

As you are aware number of calls are missing including the UpdateUser.

Here is the information from the official BoxAPI documentation.

http://developers.box.com/docs/#users-update-a-users-information

Could this be added to the next release of the product.

Kind Regards

Simon

**Comment by jhoerr** [comment]
I was not aware of the recent updates to the Users API; thanks for pointing those out.  I'll include them with the next release.

Are you sure the API is GA?  The docs say it's still in beta, and I've seen no announcement via @BoxPlatform or elsewhere...

**Comment by mascon** [comment]
We are an enterprise customer of Box. In the enterprise admin interface it states today and the GA date. I have also spoken to the team at box and its good to go.  

Only new features coming. We have a wish list for the API as long as your arm ;-).

**Comment by jhoerr** [comment]
Yup, looks like you're right.  I'll get those updates made ASAP.  How is the SDK working out for you otherwise?

**Comment by mascon** [comment]
Only started using it a couple of days ago but first impression is very well thought through. 

Just doing a analysis on building our current automation using it. They are some gaps but when I have it completed I will drop you a line to see if the feature is missing or just something I missed. 

One example would be the get user token call and then how to change the token on the fly. But as I said only just peeked at it a couple of hours so far.

**Comment by jhoerr** [comment]
Added in 7883449c6a
