### ISSUE TITLE
Enhance Collaboration Creation

### ISSUE THREAD

**Issue by mbricker** [jhoerr/box-csharp-sdk-v2#40]
It would be great to have collaboration creation enhanced so that collaborator can be an email address instead of a Box user ID. 

http://developers.box.com/docs/#collaborations-add-a-collaboration

**Comment by jhoerr** [comment]
Added `BoxManager.CreateCollaborationByEmail(...)` in cfcaffce3ba3f7aae8de2abc3882865de40c4f15
