### ISSUE TITLE
Discussions Documentation Removed from BOX SDK Site

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#44]
Just to note Box has removed the discussions from the API documentation.

Not sure if this will affect the SDK

**Comment by jhoerr** [comment]
Hrm. The Discussions APIs still work at the moment.  I suppose I'll remove support for them out when the tests start failing!

**Comment by prexer** [comment]
Wow, you guys don't miss anything.  
Yes, we were looking at which features aren't used, and looking to deprecate them.  Discussions are hardly used.

**Comment by jhoerr** [comment]
Still learning my way around Git.  Sorry for the commit spam. :)
