### ISSUE TITLE
New element for the User Update - Password Reset

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#45]
Box has included the ability for users to have their password reset from the API.

Can this be added ASAP, default value should be false.

Note from Box API Page

is_password_reset_required  Whether or not the user is required to reset password
Type: boolean

**Comment by jhoerr** [comment]
I don't see this documented on the User object.  Would you poke the Boxers and ask them to update the docs?  Thx!

**Comment by mascon** [comment]
Hi John

It is there in the documentation. See attachment.

Cheers

Simon

---

No trees were harmed in the sending of this
email, but a large number of electrons were
terribly inconvenienced.

-----Original Message-----

**Comment by jhoerr** [comment]
Thanks!

**Comment by jhoerr** [comment]
Hi Simon, this should be working now.  It appears that once the password reset is required (set to True) then there are no 'take backs.'  Let me know if it works for you.  Sorry for taking so long to get to it. :)

**Comment by prexer** [comment]
Y, it's a one-way gate.  You can set it to true, and then the next time the user trys to login, we force them to reset their password.  This is only allowed to be set by admins.

**Comment by jhoerr** [comment]
Thanks for the behavior confirmation, Peter.  Closing as fixed.
