### ISSUE TITLE
BoxManager.DoGetFolderSync

### ISSUE THREAD

**Issue by ericrtodd** [jhoerr/box-csharp-sdk-v2#46]
In DoGetFolderSync, the total_count attribute is compared to the item_collection count.  When the total_count does not match the item_collection count, another request is made with the offset of the original item_collection count.  Is there a justification for this?  I haven't found anything at developer.box.com mentioning prescribed behavior for a count mismatch.

I have come across a scenario where the item_count and item_collection count do not match (item_count > item_collection count), but the item_count is incorrect.  So when the BoxManager attempts to make another request with the offset, I end up with a 500 response and my total results are lost.  I filed a support ticket with Box to try and clarify, and the support representative stated that I should rely on the item_collection count instead of the item_count.

If you have run across a scenario, or documentation, that prescribes the additional request I would like to send it to the Box representative that I am in contact with.  Otherwise, do you think that this necessitates a change?

**Comment by jhoerr** [comment]
Hi Eric, this is a bug.  Good eye!  Thanks for reporting it.

**Comment by jhoerr** [comment]
Eric, can you please verify that this fix works for you?

**Comment by jhoerr** [comment]
Hearing no objection, I'm closing this.  Feel free to re-open it if there's still a problem.
