### ISSUE TITLE
Missing Features for Email Alias

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#5]
Can you please implement the following API V2 feature ASAP

Get All Email Aliases for a User

Add an Email Alias for a User

Remove an Email Alias from a User

Changing a User’s Primary Login (I think this is just the standard Update User call but you will know better)

Box has released this feature today and as it's one I have been chasing so it would be nice it we could start using it quickly.

**Comment by jhoerr** [comment]
Thanks for the heads up!  I'm nearly finished with the OAuth2 implementation; should have it out today.  These will be next on the list.

**Comment by jhoerr** [comment]
Implemented as of a2447af111
