### ISSUE TITLE
Integreting my web site with box.net.

### ISSUE THREAD

**Issue by ankurshah32** [jhoerr/box-csharp-sdk-v2#54]
Let me tell my requirements what I want to implement on my site.
1. User register on my site.
2. Upload some files on my site and i will process these file.
3. Now user can download these file via link.

Now what i want to do is that user who is register on my site and given access to me or my site via OAuth.
I wanna to download the files from user box.net to my site and process these files and put it back to user box.net.

Before starting development process i have question.
What is the best and simplest way to do this please elaborate?
What all inputs required form user needed to access the files from box.net?

**Comment by jhoerr** [comment]
Hi Ankur,

There is an [MVC-based example](https://github.com/jhoerr/box-csharp-sdk-v2.sample.oauth) that shows how to authenticate a Box user.  Once you have an access token, you can refer to the [usage example](https://github.com/jhoerr/box-csharp-sdk-v2/blob/master/readme.markdown#usage-example) to learn how to work with files.
