### ISSUE TITLE
Operation has timed out for read

### ISSUE THREAD

**Issue by prasannalakshmihost** [jhoerr/box-csharp-sdk-v2#58]
Hi jhoerr,

We are getting 'The operation has timed out' error with httpstatuscode of badrequest when calling boxMangaer.Read(string id) for downloading a file as stream for files with size around 90MB. Is there a way to increase the timeout from our side?

**Comment by jhoerr** [comment]
There isn't a way to increase the timeout. But I don't think this is an HTTP issue -- I think you'd be getting a different error if it was.
