### ISSUE TITLE
Missing Role Level

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#6]
A user can have the following levels

User
Co-admin
Admin

Currently only User and Admin are supported.  This results in co-admin's being incorrectly labelled as Users.

I think it is this that needs to be changed

namespace BoxApi.V2.Model.Enum
{
    public enum UserRole
    {
        [EnumMember(Value = "user")] User,
        [EnumMember(Value = "admin")] Admin,
    }
}

to this

namespace BoxApi.V2.Model.Enum
{
    public enum UserRole
    {
        [EnumMember(Value = "user")] User,
        [EnumMember(Value = "coadmin")] CoAdmin,
        [EnumMember(Value = "admin")] Admin,
    }
}

**Comment by jhoerr** [comment]
Fixed in d3863fdd08.  Please feel free to issue pull requests for fixes like this.
