### ISSUE TITLE
Get Enterprise Users Method [Enhancement]

### ISSUE THREAD

**Issue by YakkingYak** [jhoerr/box-csharp-sdk-v2#60]
Will the "Get Enterprise Users" method be added to the .NET SDK anytime soon?
https://box-content.readme.io/reference#get-all-users-in-an-enterprise

Also, is there a way to get a list of external users who are collaborators in a folder (or it's subfolder)?

**Comment by jhoerr** [comment]
This SDK supports that (see BoxManager.GetUsers) but active development has otherwise ceased. Are you aware that Box has an official Windows SDK now?

**Comment by YakkingYak** [comment]
I thought this was the official SDK...

**Comment by YakkingYak** [comment]
Oops. I meant to add this to box/box-windows-sdk-v2 and not jhoerr/box-csharp-sdk-v2. Too many tabs open! :D
