### ISSUE TITLE
boxManager.GetFolder(Folder.Root)

### ISSUE THREAD

**Issue by hari70** [jhoerr/box-csharp-sdk-v2#61]
This used to work. Dont know what happened on the Box front.

Now getting Bad Request error. Using fiddler I see that the first request is successfull. But it keeps on retrying with the different offset 300 times until it reaches 301000 and errors out.

I am not even passing the offset but simply using boxManager.getFolder("0");

Any help is greatlyappreciated. Thanks!

ConfigWriter configWriter = new ConfigWriter();
            Log("Refresh Token = " + REFRESH_TOKEN);
            tokenProvider = new TokenProvider(CLIENT_ID, CLIENT_SECRET);
            newToken = tokenProvider.RefreshAccessToken(REFRESH_TOKEN);
            ACCESS_TOKEN = newToken.AccessToken;
            Log("New Access Token = " + ACCESS_TOKEN);
            REFRESH_TOKEN = newToken.RefreshToken;
            Log("New Refresh Token = " + REFRESH_TOKEN);
            configWriter.updateConfig ("Refresh_Token", REFRESH_TOKEN);

```
        boxManager = new BoxManager(ACCESS_TOKEN);
        //var adminClient = boxJWT.AdminClient(adminToken);
        Log("User" + boxManager.Me());
        rootFolder = boxManager.GetFolder(Folder.Root);
```

**Comment by jhoerr** [comment]
Hi @hari70, this SDK is no longer maintained. I'd recommend switching to Box's [official Windows SDK](https://github.com/box/box-windows-sdk-v2).

**Comment by hari70** [comment]
Thanks @jhoerr
