### ISSUE TITLE
Calling BoxClient.GetEmailAliases causes unhandled excetion

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#8]
Calling the function BoxClient.GetEmailAliases("myemail@address.com") causes an unhandled exception.

I fully understand that this should be called with the BOXID but this was not clear in the description.

**Comment by jhoerr** [comment]
Which is unclear: the method documentation or the exception information?

**Comment by mascon** [comment]
Actually I think we can close this one.  It says userID and that is clearly the BOXID

**Comment by jhoerr** [comment]
Okie dokie.
